USE master;

GO
ALTER DATABASE QuanLiNganHang SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

GO
DROP DATABASE QuanLiNganHang;

GO
CREATE DATABASE QuanLiNganHang;

GO
USE QuanLiNganHang;

GO
CREATE TABLE NganHang (
    MaNH INT PRIMARY KEY,
    TenNH NVARCHAR(100) NOT NULL
);

GO
CREATE TABLE ChiNhanh (
    MaCN INT PRIMARY KEY,
    MaNH INT NOT NULL,
    ThanhPhoCN NVARCHAR(100),
    TaiSan DECIMAL(18, 2) NOT NULL DEFAULT 0
);

GO
ALTER TABLE ChiNhanh ADD CONSTRAINT FK_ChiNhanh_NganHang
    FOREIGN KEY (MaNH) REFERENCES NganHang(MaNH) ON DELETE CASCADE

GO
CREATE TABLE KhachHang (
    MaKH INT PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255) NOT NULL
);

GO
CREATE TABLE TaiKhoanVay (
    MaCN INT NOT NULL,
    SoTKV INT NOT NULL,

    MaKH INT NOT NULL ,
    SoTienVay DECIMAL(18, 2) NOT NULL DEFAULT 0
    
    PRIMARY KEY (MaKH, SoTKV)
);

GO
ALTER TABLE TaiKhoanVay ADD CONSTRAINT FK_TaiKhoanVay_KhachHang
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE;

GO
ALTER TABLE TaiKhoanVay ADD CONSTRAINT FK_TaiKhoanVay_ChiNhanh
    FOREIGN KEY (MaCN) REFERENCES ChiNhanh(MaCN) ON DELETE CASCADE

GO
CREATE TABLE TaiKhoanGoi (
    MaCN INT NOT NULL,
    SoTKG INT NOT NULL,

    MaKH INT NOT NULL,
    SoTienGoi DECIMAL(18, 2) NOT NULL DEFAULT 0,

    PRIMARY KEY (MaKH, SoTKG)
);

GO
ALTER TABLE TaiKhoanGoi ADD CONSTRAINT FK_TaiKhoanGoi_KhachHang
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE;

GO
ALTER TABLE TaiKhoanGoi ADD CONSTRAINT FK_TaiKhoanGoi_ChiNhanh
    FOREIGN KEY (MaCN) REFERENCES ChiNhanh(MaCN) ON DELETE CASCADE;
