USE master;

GO
ALTER DATABASE TrungTamNgoaiNgu SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

GO
DROP DATABASE TrungTamNgoaiNgu;

GO
CREATE DATABASE TrungTamNgoaiNgu;

GO
USE TrungTamNgoaiNgu;

GO
CREATE TABLE KhoaHoc (
    MaKH INT PRIMARY KEY,

    TenKH NVARCHAR(100) NOT NULL,
    BD DATE NOT NULL,
    KT DATE NOT NULL
);

GO
CREATE TABLE HocVien (
    MaHV INT PRIMARY KEY,

    Ho NVARCHAR(50) NOT NULL,
    Ten NVARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi NVARCHAR(255),
    NgheNghiep NVARCHAR(100)
);

GO
CREATE TABLE GiaoVien (
    MaGV INT PRIMARY KEY,

    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi NVARCHAR(255)
);

GO
CREATE TABLE LopHoc (
    MaLH INT PRIMARY KEY,

    TenLop NVARCHAR(100) NOT NULL,
    MaKH INT NOT NULL,
    MaGV INT,
    SiSo INT NOT NULL DEFAULT 0,
    LopTRG BIT NOT NULL
);

GO
ALTER TABLE LopHoc ADD CONSTRAINT FK_LopHoc_KhoaHoc
    FOREIGN KEY (MaKH) REFERENCES KhoaHoc(MaKH) ON DELETE CASCADE;

GO
ALTER TABLE LopHoc ADD CONSTRAINT FK_LopHoc_GiaoVien
    FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV) ON DELETE CASCADE;

GO
CREATE TABLE BienLai (
    MaBL INT NOT NULL,
    SoBL NVARCHAR(50) NOT NULL,

    MaKH INT NOT NULL,
    MaLH INT NOT NULL,
    MaHV INT NOT NULL,
    Diem DECIMAL(5,2),
    KetQua NVARCHAR(50),
    XepLoai NVARCHAR(50),
    TienNop DECIMAL(18, 2) NOT NULL DEFAULT 0,
    
    PRIMARY KEY (MaBL, SoBL)
);

GO
ALTER TABLE BienLai ADD CONSTRAINT FK_BienLai_KhoaHoc
    FOREIGN KEY (MaKH) REFERENCES KhoaHoc(MaKH) ON DELETE CASCADE;

GO
ALTER TABLE BienLai ADD CONSTRAINT FK_BienLai_LopHoc
    FOREIGN KEY (MaLH) REFERENCES LopHoc(MaLH); 

GO
ALTER TABLE BienLai ADD CONSTRAINT FK_BienLai_HocVien
    FOREIGN KEY (MaHV) REFERENCES HocVien(MaHV) ON DELETE CASCADE;